SOURCES := $(shell find . -type f -name '*.go' -not -path './vendor/*')

dev:
	@goimports -l -w ${SOURCES}
	@go vet . ./lib/...
	@go test . ./lib/...
	go install 

build:
	go fmt . ./lib/...
	go vet . ./lib/...
	staticcheck . ./lib/...
	gosimple . ./lib/...
	go test . ./lib/...
	go install -race .
	cyberspace

js:
	./node_modules/.bin/webpack -d -w --progress

compile:
	./node_modules/.bin/webpack -p --progress
	go install .
